P1/TextSearchAndAdvancedSQL/Models/Document/AddTextVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TextSearchAndAdvancedSQL.Models.Document
{
    public class AddTextVM
    {
        [Required(ErrorMessage = "Document title is required")]
        [MaxLength(200, ErrorMessage = "Title must be 200 characters or less")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Document keywords are required")]
        [MaxLength(200, ErrorMessage = "Keywords must have 200 characters or less")]
        public string Keywords { get; set; }

        [Required(ErrorMessage = "Summary is required")]
        [MaxLength(1000, ErrorMessage = "Summary must have 1000 characters or less")]
        public string Summary { get; set; }

        [Required(ErrorMessage = "Body is required")]
        [MaxLength(10000, ErrorMessage = "Body must have 10000 characters or less")]
        public string Body { get; set; }
    }
}

P1/TextSearchAndAdvancedSQL/Models/Document/AnalyzeVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TextSearchAndAdvancedSQL.BLL.UC;

namespace TextSearchAndAdvancedSQL.Models.Document
{
    public class AnalyzeVM
    {
        [Display(Name = "Start date")]
        [Required(ErrorMessage = "Start date is required")]
        [DataType(DataType.Date)]
        public DateTime Start { get; set; } = DateTime.Now;

        [Display(Name = "End date")]
        [Required(ErrorMessage = "End date is required")]
        [DataType(DataType.Date)]
        public DateTime End { get; set; } = DateTime.Now;

        [Required(ErrorMessage = "Granulation is required")]
        public string Granulation { get; set; } = "Day";

        public Tuple<List<string>, List<AnalyzeUseCase.Result>> Response { get; set; } 
            = new Tuple<List<string>, List<AnalyzeUseCase.Result>>(new List<string>(), new List<AnalyzeUseCase.Result>());
    }
}

P1/TextSearchAndAdvancedSQL/Models/Document/SearchVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TextSearchAndAdvancedSQL.Models.Document
{
    public class SearchVM
    {
        public class Document
        {
            public int Id { get; set; }

            public string Title { get; set; }

            public double Rank { get; set; }
        }

        [Display(Name = "Search patterns")]
        [Required(ErrorMessage = "Search pattern is required")]
        [MaxLength(200, ErrorMessage = "Search pattern must be 200 characters or less")]
        public string Patterns { get; set; }

        [Display(Name = "Logical operator")]
        [Required(ErrorMessage = "Logical operator is required")]
        public string Operator { get; set; } = "And";

        [Display(Name = "Search type")]
        [Required(ErrorMessage = "Search type is required")]
        public string SearchType { get; set; } = "Semantic";

        public string SQLQuery { get; set; } = string.Empty;

        public IEnumerable<Document> Documents { get; set; } = new List<Document>();
    }
}

P1/TextSearchAndAdvancedSQL/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TextSearchAndAdvancedSQL.BLL.Model;
using TextSearchAndAdvancedSQL.BLL.UC;
using TextSearchAndAdvancedSQL.Models.Document;

namespace TextSearchAndAdvancedSQL.Controllers
{
    public class DocumentController : Controller
    {
        // GET: Search
        public ActionResult Index()
        {
            return RedirectToAction(nameof(Search));
        }

        public ActionResult Details(int id)
        {
            return View(new GetDocumentUseCase().Execute(id));
        }

        // GET: AddText
        public ActionResult AddText()
        {
            return View(new AddTextVM());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddText(AddTextVM vm)
        {
            var doc = new Document();
            try { doc.Title = vm.Title; } catch (Exception e) { ModelState.AddModelError(nameof(AddTextVM.Title), e.Message); }
            try { doc.Summary = vm.Summary; } catch (Exception e) { ModelState.AddModelError(nameof(AddTextVM.Summary), e.Message); }
            try { doc.Keywords = vm.Keywords; } catch (Exception e) { ModelState.AddModelError(nameof(AddTextVM.Keywords), e.Message);  }
            try { doc.Body = vm.Body; } catch (Exception e) { ModelState.AddModelError(nameof(AddTextVM.Body), e.Message); }

            if(!ModelState.IsValid)
            {
                return View(vm);
            }

            if (new AddTextUseCase().Execute(doc))
            {
                return RedirectToAction(nameof(Search), new { title = doc.Title });
            }
            else
            {
                return View(vm);
            }
        }

        // GET: Search
        public ActionResult Search(string title = "")
        {
            return View(new SearchVM { Patterns = title, Operator = "and", SearchType = "semantic" });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(SearchVM vm)
        {
            var patterns = vm.Patterns.Split('"')
                     .Select((element, index) => index % 2 == 0  // If even index
                                           ? element.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries)  // Split the item
                                           : new string[] { element })  // Keep the entire item
                     .SelectMany(element => element).ToList();
            var op = "and".Equals(vm.Operator, StringComparison.InvariantCultureIgnoreCase) ? SearchUseCase.Operator.And : SearchUseCase.Operator.Or;

            SearchUseCase.Response response = null;
            if ("semantic".Equals(vm.SearchType, StringComparison.InvariantCultureIgnoreCase))
            {
                response = new SemanticSearchUseCase().Execute(patterns, op);
            }
            else
            {
                response = new FuzzySearchUseCase().Execute(patterns, op);
            }

            vm.SQLQuery = response.SQLQuery;

            vm.Documents = (from d in response.Results
                            select new SearchVM.Document
                            {
                                Id = d.Item1,
                                Title = d.Item2,
                                Rank = d.Item3,
                            }).ToList();

            return View(vm);
        }

        // GET: Analyze
        public ActionResult Analyze()
        {
            return View(new AnalyzeVM());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Analyze(AnalyzeVM vm)
        {
            var gran = "day".Equals(vm.Granulation, StringComparison.InvariantCultureIgnoreCase) ? AnalyzeUseCase.Granulation.Days : AnalyzeUseCase.Granulation.Hours;
            vm.Response = new AnalyzeUseCase().Execute(vm.Start, vm.End, gran);
            return View(vm);
        }
    }
}

P1/TextSearchAndAdvancedSQL/Views/Document/AddText.cshtml
@model TextSearchAndAdvancedSQL.Models.Document.AddTextVM

@{
    ViewBag.Title = "Add text";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h2>Add text</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Keywords, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Keywords, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Keywords, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Summary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Summary, new { @class = "form-control", rows = 3 })
                @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, new { @class = "form-control", rows = 20 })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

P1/TextSearchAndAdvancedSQL/Views/Document/Analyze.cshtml
@model TextSearchAndAdvancedSQL.Models.Document.AnalyzeVM

@{
    ViewBag.Title = "Analyze";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Analyze</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control", @type = "date", @value = Model.Start.ToShortDateString() } })
                @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.End, new { htmlAttributes = new { @class = "form-control", @type = "date", @value = Model.End.ToShortDateString() } })
                @Html.ValidationMessageFor(model => model.End, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Granulation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="radio-inline">
                    @Html.RadioButtonFor(model => model.Granulation, "Day") Days
                </label>
                <label class="radio-inline">
                    @Html.RadioButtonFor(model => model.Granulation, "Hour") Hours
                </label>
                @Html.ValidationMessageFor(model => model.Granulation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Analyze" class="btn btn-primary" />
            </div>
        </div>

        <div class="container">
            <h4>Results</h4>
            <hr />
            <table class="table">
                <thead>
                    <tr>
                        <th>Query</th>
                        @foreach(var h in Model.Response.Item1)
                        {
                            <th>@h</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var d in Model.Response.Item2)
                    {
                        <tr>
                            <td>@d.SearchPattern</td>
                            @foreach(var c in d.Times)
                            {
                                <td>@c</td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

P1/TextSearchAndAdvancedSQL/Views/Document/Details.cshtml
@model TextSearchAndAdvancedSQL.BLL.Model.Document

@{
    ViewBag.Title = Model.Title;
}

<h2>@Model.Title</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Keywords)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Keywords)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Summary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Summary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

    </dl>
</div>

P1/TextSearchAndAdvancedSQL/Views/Document/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/Document/index.js")
}

P1/TextSearchAndAdvancedSQL/Views/Document/Search.cshtml
@model TextSearchAndAdvancedSQL.Models.Document.SearchVM

@{
    ViewBag.Title = "Search";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Search</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Patterns, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Patterns, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Patterns, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Operator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="radio-inline">
                    @Html.RadioButtonFor(model => model.Operator, "And") And
                </label>
                <label class="radio-inline">
                    @Html.RadioButtonFor(model => model.Operator, "Or") Or
                </label>
                @Html.ValidationMessageFor(model => model.Operator, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SearchType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="radio-inline">
                    @Html.RadioButtonFor(model => model.SearchType, "Semantic") Based on morphology & semantic
                </label>
                <label class="radio-inline">
                    @Html.RadioButtonFor(model => model.SearchType, "Fuzzy") Fuzzy string matching
                </label>
                @Html.ValidationMessageFor(model => model.SearchType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </div>

        @if (!string.IsNullOrEmpty(Model.SQLQuery))
        {
            <div class="container">
                <h4>SQL Query</h4>
                <hr />
                <div class="col-md-12">
                    <textarea class="form-control valid" cols="20" id="SQLQuery" name="SQLQuery" readonly="true" rows="10" aria-invalid="false">@Html.Raw(Model.SQLQuery)</textarea>
                </div>
            </div>
        }

        <div class="container">
            <h4>Search results (@Model.Documents.Count())</h4>
            <hr />
            <table class="table">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th colspan="2">Rank</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var d in Model.Documents.AsEnumerable())
                    {
                        <tr>
                            <td>@Html.Raw(d.Title)</td>
                            <td>@d.Rank</td>
                            <td>@Html.ActionLink("View", "Details", "Document", new { id = d.Id }, new { @class = "btn btn-default" })</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

P1/TextSearchAndAdvancedSQL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - jk47975</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("jk47975", "Index", "Document", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Search", "Search", "Document")</li>
                    <li>@Html.ActionLink("Add", "AddText", "Document")</li>
                    <li>@Html.ActionLink("Analyze", "Analyze", "Document")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Jan Kelemen, 0036479753</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/Shared/layout.js")
    @RenderSection("scripts", required: false)
</body>
</html>